# Generated by Django 4.2.6 on 2024-02-12 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.loginlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='loginaction',
            constraint=models.UniqueConstraint(fields=('list', 'user', 'date'), name='login_action_unique', violation_error_message='A login action already exists!'),
        ),
    ]
